### PR TITLE
WIP: fix links by using relative ones to markdown files

### PR DESCRIPTION
**Pull request by Midnighter**
* [ ] fix #(issue number)
* [ ] description of feature/fix
* [ ] tests added/passed
* [ ] add an entry to the [changelog](../CHANGELOG.md)

See answer to my question in the [mkdocs discussions](https://github.com/mkdocs/mkdocs/discussions/3230#discussioncomment-6020774).

### CODE REVIEW

**Comment by Midnighter** [comment]
It's still work in progress but I'm removing draft status so that I can enable this branch on readthedocs and we can test links there.

**Comment by Midnighter** [comment]
Looks like that's working, e.g., https://taxpasta.readthedocs.io/en/docs-links/tutorials/getting-started/. So now I just need to go through all links in all markdown files 😝

**Review by jfy133 — COMMENTED** [review]
Are you sure this works when rendered? I'm pretty sure when I had done this it breaks because the URL looks for a markdown that doesn't exist because the file has been converted to html?

**Comment by jfy133** [comment]
Ok just saw the comment...I believe you 😬. I'm also happy to take this over it it would help!

**Comment by Midnighter** [comment]
> Ok just saw the comment...I believe you grimacing. I'm also happy to take this over it it would help!

Thank you for the offer. I hope I caught all of the necessary changes using a pattern search. Just need to fix this one link now.

**Pull request merged**
