### PR TITLE
Support Metaphlan4 format

### LINKED ISSUE #111: [BUG] CRITICAL error when parsing MetaPhlAn4's output
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I'm getting the following error message when trying to parse MetaPhlAn4's outputs with taxpasta.

```
[21:40:18] CRITICAL Error in sample 'ERR7569997' with profile 'metaphlan/ERR7569997.txt'.          merge.py:422
           CRITICAL     schema_context  ... index                                                  merge.py:425
                    4  DataFrameSchema  ...  None
                    0           Column  ...     0
                    1           Column  ...  None
                    2           Column  ...  None
                    3           Column  ...  None

                    [5 rows x 6 columns]
```

I wonder if this has anything to do with the non-standard taxa in MetaPhlAn4's output (see example below).

```
k__Bacteria|p__Atribacterota|c__CFGB8897|o__OFGB8897|f__FGB8897 2|67818|||      0.01864
```
Full MetaPhlAn4 output available [here](https://github.com/taxprofiler/taxpasta/files/11860987/ERR7569999.txt).

### Code sample

```bash
taxpasta merge -o taxpasta/taxpasta.tsv --taxonomy /home/geoadmin/geonomecontainer/KMCP/taxdump --profiler metaphlan --add-lineage metaphlan/*.txt
```

### Environment

<details>
### Package Information

| Package  | Version |
|:---------|--------:|
| taxpasta |   0.3.0 |

### Dependency Information

|           Package            |   Version   |
|:-----------------------------|------------:|
| bash-kernel                  | **missing** |
| biom-format                  |      2.1.15 |
| depinfo~                     | **missing** |
| jupyter                      | **missing** |
| mkdocs-awesome-pages-plugin~ | **missing** |
| mkdocs-exclude~              | **missing** |
| mkdocs-material~             | **missing** |
| mkdocstrings[python]~        | **missing** |
| numpy~                       | **missing** |
| odfpy                        | **missing** |
| openpyxl                     | **missing** |
| pandas~                      | **missing** |
| pandera~                     | **missing** |
| pre-commit                   | **missing** |
| pyarrow                      |      11.0.0 |
| rich                         |      13.4.2 |
| tabulate~                    | **missing** |
| taxopy~                      | **missing** |
| tox~                         | **missing** |
| typer~                       | **missing** |

### Build Tools Information

|  Package   | Version |
|:-----------|--------:|
| pip        |  23.0.1 |
| setuptools |  67.4.0 |
| wheel      |  0.38.4 |

### Platform Information

|         |                          |
|:--------|-------------------------:|
| Linux   | 5.15.0-1037-azure-x86_64 |
| CPython |                   3.11.0 |
</details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by TheOafidian**
The amount of rows before the profile differs between metaphlan3 and 4. Therefore taxpasta was not working on metaphlan4 output under the current circumstances. Since the header is formatted the same between both versions, a quick scan for the first field of the header could ensure the table is read from the right line in both formats.

I did not find any issues raised for this, so I just added the code I've used on my local example of to get it to work on the new format.

* [x] fix #111
* [x] description of feature/fix
* [x] tests added/passed
* [ ] add an entry to the [changelog](../CHANGELOG.md)

### CODE REVIEW

**Comment by jfy133** [comment]
Thanks @TheOafidian !

I'll leave this up to @Midnighter to decide if he's OK with this system, however I can predict already he will ask for example test data to be added from MetaPhlAn4. Would you be able to upload some too? (Can be the one you found the issue from, but you can manually remove any sample-identification info)

**Comment by Midnighter** [comment]
Just to be sure, the extra line is a default feature of MetaPhlAn4 and not due to some option that you have set?

**Comment by TheOafidian** [comment]
Hey @Midnighter, don't have time to go look for an example on my work laptop right now, but indeed I've used default args. I've found [in the Metaphlan4 tutorial an example of output](https://github.com/biobakery/biobakery/wiki/metaphlan4#131-the-metaphlan-taxonomic-profile) where this new line is also present like it was in my data.

**Review by Midnighter — CHANGES_REQUESTED** [review]
Thank you for the contribution @TheOafidian, and apologies for the wait. I'm afraid that the logic needs to be slightly more complicated, as the `read` method is designed to accept both buffers, like `StringIO`, and path-like objects, such as `str` or `Path`.

If you don't feel like tackling that, I'm happy to take over from here. As mentioned in the comments, adding one or two MetaPhlAn4 files to the test data is also needed.

**Comment by jfy133** [comment]
Some test data thanks to @apcamago

https://github.com/taxprofiler/taxpasta/issues/111#issuecomment-1606547819

**Review by Midnighter — APPROVED** [review]

**Pull request merged**
